// Code generated by "stringer -type=ColumnChangeType"; DO NOT EDIT

package models

import "fmt"

const _ColumnChangeType_name = "ColumnChangeType_SameColumnChangeType_TypeColumnChangeType_CommentColumnChangeType_NotNullColumnChangeType_DefaultColumnChangeType_ExtraColumnChangeType_Order"

var _ColumnChangeType_index = [...]uint8{0, 21, 42, 66, 90, 114, 136, 158}

func (i ColumnChangeType) String() string {
	if i < 0 || i >= ColumnChangeType(len(_ColumnChangeType_index)-1) {
		return fmt.Sprintf("ColumnChangeType(%d)", i)
	}
	return _ColumnChangeType_name[_ColumnChangeType_index[i]:_ColumnChangeType_index[i+1]]
}
